# Generated by Django 4.2.3 on 2023-07-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movieapp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actors', models.CharField(max_length=500)),
                ('Awards', models.CharField(max_length=500)),
                ('BoxOffice', models.IntegerField(max_length=20)),
                ('Country', models.CharField(max_length=80)),
                ('DVD', models.DateTimeField()),
                ('Director', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=200)),
                ('Language', models.CharField(max_length=200)),
                ('Metascore', models.IntegerField(max_length=20)),
                ('Plot', models.CharField(max_length=700)),
                ('Poster', models.CharField(max_length=200)),
                ('Production', models.CharField(max_length=100)),
                ('Rated', models.CharField(max_length=10)),
                ('Ratings', models.CharField(max_length=700)),
                ('Released', models.DateTimeField()),
                ('Response', models.BooleanField(default=False)),
                ('Runtime', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=225)),
                ('Type', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=25)),
                ('Writer', models.CharField(max_length=100)),
                ('Year', models.IntegerField(max_length=10)),
                ('imdbID', models.CharField(max_length=25)),
                ('imdbRating', models.FloatField(max_length=100)),
                ('imdbVotes', models.FloatField(max_length=50)),
                ('isSaved', models.BooleanField(default=False)),
            ],
        ),
    ]
