# Generated by Django 4.2.3 on 2023-07-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_usersavedmovies_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedmovies',
            name='DVD',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usersavedmovies',
            name='Released',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
