# Generated by Django 4.2.3 on 2023-08-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_usersavedmovies_boxoffice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedmovies',
            name='Plot',
            field=models.CharField(max_length=2000),
        ),
    ]
